#
# https://waha.devlike.pro/docs/how-to/install/
# Here's we provide a simple example of how to install WAHA using Docker Compose.
#
# We're assuming you have Docker and Docker Compose installed.
# If you don't have Docker Compose installed, you can follow the official guide:
# https://docs.docker.com/compose/install/
#

services:
  waha:
    restart: always

    # We strongly recommend using the pinned version of WAHA
    # https://waha.devlike.pro/docs/how-to/engines/#versions
    # image: devlikeapro/waha-plus:latest-2024.7.6 # 'latest' is not mistaken here
    #
    # Multiple images are available
    # https://waha.devlike.pro/docs/how-to/engines/#docker-images
    # image: devlikeapro/waha-plus:chrome
    #
    image: devlikeapro/waha-plus:latest # or devlikeapro/waha:latest if you're using WAHA Core

    # The first port can be any free port you want
    # The second port must be the same as WHATSAPP_API_PORT or 3000 by default
    # Consider using the same port for simplicity
    ports:
      - '127.0.0.1:3000:3000/tcp'
      # NOTE: if you're using HTTP, you can use the following port mapping
      #- '80:3000/tcp'
      # NOTE: if you're using HTTPS, you can use the following port mapping
      #- '443:3000/tcp'

    volumes:
      # Store sessions in the .sessions folder (comment it if you're using MongoDB)
      # Doesn't work with WAHA Core
      - './.sessions:/app/.sessions'

      # https://waha.devlike.pro/docs/how-to/storages/#save-media-files-between-the-container-restarts
      - './.media:/app/.media'

    env_file:
      - .env

  # NOTE: Only if you're using MongoDB
  # https://waha.devlike.pro/docs/how-to/storages/#sessions---mongodb
  # Comment this block if you're using MongoDB
#  mongodb:
#    image: mongo
#    container_name: mongodb
#    ports:
#      - '127.0.0.1:27017:27017/tcp'
#    volumes:
#      - mongodb_data:/data/db
#    restart: always

# NOTE: Only if you're using S3 to save media files
# https://waha.devlike.pro/docs/how-to/storages/#media---s3
# Comment this block if you're using AWS S3
#  minio:
#    image: quay.io/minio/minio
#    container_name: minio
#    restart: always
#    ports:
#      - '127.0.0.1:9000:9000'
#      - '127.0.0.1:9001:9001'
#    environment:
#      MINIO_REGION: 'eu-west-2'
#      MINIO_ROOT_USER: 'minioadmin'
#      MINIO_ROOT_PASSWORD: 'minioadmin'
#    volumes:
#      - minio_data:/data
#    command: server /data --console-address ":9001"

volumes:
  # NOTE: Only if you're using MongoDB
  mongodb_data: {}
  minio_data: {}
